name: Terraform Per-Layer
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        layer: [01_gcp-compute, 02_gcp-network]
 
    defaults:
      run:
        shell: bash
 
    steps:
      # 1 Checkout code
      - name: Checkout
        uses: actions/checkout@v3
 
      # 2 Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0
 
      # 3 Authenticate GCP
      # - name: Setup GCP Credentials
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.GCP_SA_KEY }}
 
      # 4 Configure backend (GCS)
      - name: Terraform Init
        working-directory: ${{ matrix.layer }}
        run: terraform init -backend-config="bucket=${{ secrets.GCS_BUCKET }}" -reconfigure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      # 5 Terraform Validate
      - name: Terraform Validate
        working-directory: ${{ matrix.layer }}
        run: terraform validate
 
      # 6 Terraform Plan
      - name: Terraform Plan
        working-directory: ${{ matrix.layer }}
        run: terraform plan -out=tfplan -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

 
      # 7 Terraform Apply
      - name: Terraform Apply
        working-directory: ${{ matrix.layer }}
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

 
